---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmstate-operator
  namespace: nmstate
  labels:
    app: kubernetes-nmstate-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubernetes-nmstate-operator
  template:
    metadata:
      labels:
        app: kubernetes-nmstate-operator
        name: kubernetes-nmstate-operator
    spec:
      serviceAccountName: nmstate-operator
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nmstate-operator
          args:
          - --v=production
          # Replace this with the built image name
          image: registry:5000/nmstate/kubernetes-nmstate-operator
          imagePullPolicy: Always
          command:
          - kubernetes-nmstate
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERATOR_NAME
              value: "kubernetes-nmstate-operator"
            - name: ENABLE_PROFILER
              value: "False"
            - name: PROFILER_PORT
              value: "6060"
            - name: RUN_OPERATOR
              value: ""
            - name: HANDLER_IMAGE
              value: registry:5000/nmstate/kubernetes-nmstate-handler
            - name: HANDLER_IMAGE_PULL_POLICY
              value: Always
            - name: HANDLER_NAMESPACE
              value: nmstate
